version: '3.8'

services:
  postgres:
    container_name: ebb_testdb
    image: postgres:latest
    environment:
      POSTGRES_USER: ebb
      POSTGRES_PASSWORD: ebb
      POSTGRES_DB: ebb
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
