version: '3.8'

services:
  sample:
    container_name: ebb_sample_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ebb
      POSTGRES_PASSWORD: ebb
      POSTGRES_DB: ebb
      PGDATA: /data/postgres
    volumes:
      - postgres-db-sample:/data/postgres
    ports:
      - "5431:5432"

  prod:
    container_name: ebb_prod_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ebb
      POSTGRES_PASSWORD: ebb
      POSTGRES_DB: ebb
      PGDATA: /data/postgres
    volumes:
      - postgres-db-prod:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db-sample:
    driver: local
  postgres-db-prod:
    driver: local