/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 *
 * Generated by: https://openapi-generator.tech
 */

/// AcademicOrganization : An Academic Organization at Waterloo is similar to a department

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AcademicOrganization {
    /// Unique Code of this Academic Organization
    #[serde(
        rename = "code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub code: Option<Option<String>>,
    /// The Name for this Academic Organization, most often the display name
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The short description for this Academic Organization
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The formal description for this Academic Organization, most often used in official capacity
    #[serde(
        rename = "descriptionFormal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description_formal: Option<Option<String>>,
    /// The Code for the Campus that this Academic Organization is assigned to
    #[serde(
        rename = "associatedCampusCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub associated_campus_code: Option<Option<String>>,
}

impl AcademicOrganization {
    /// An Academic Organization at Waterloo is similar to a department
    pub fn new() -> AcademicOrganization {
        AcademicOrganization {
            code: None,
            name: None,
            description: None,
            description_formal: None,
            associated_campus_code: None,
        }
    }
}
