/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Changed {
    #[serde(
        rename = "predicates",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub predicates: Option<Option<Vec<String>>>,
    #[serde(
        rename = "datatype",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub datatype: Option<Option<String>>,
    #[serde(
        rename = "callback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub callback: Option<Option<String>>,
}

impl Changed {
    pub fn new() -> Changed {
        Changed {
            predicates: None,
            datatype: None,
            callback: None,
        }
    }
}
