/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct En1 {
    #[serde(rename = "robots", skip_serializing_if = "Option::is_none")]
    pub robots: Option<Box<crate::models::Robots>>,
}

impl En1 {
    pub fn new() -> En1 {
        En1 { robots: None }
    }
}
