/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Feature : Feature of location collection



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Feature {
    /// Type of Feature
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::Location>>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<Box<crate::models::Geometry>>,
}

impl Feature {
    /// Feature of location collection
    pub fn new() -> Feature {
        Feature {
            r#type: None,
            properties: None,
            geometry: None,
        }
    }
}


