/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FieldCombos {
    #[serde(rename = "und", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub und: Option<Option<Vec<crate::models::Und>>>,
}

impl FieldCombos {
    pub fn new() -> FieldCombos {
        FieldCombos {
            und: None,
        }
    }
}


