/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Geometry : Represents Geometry data of the Feature



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Geometry {
    /// Type of geometry
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// Latitude and Longitude collection of this location
    #[serde(rename = "coordinates", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coordinates: Option<Option<Vec<f64>>>,
}

impl Geometry {
    /// Represents Geometry data of the Feature
    pub fn new() -> Geometry {
        Geometry {
            r#type: None,
            coordinates: None,
        }
    }
}


