/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ImportantDate : An Important Date is an event at a time that has significance to the Waterloo community



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImportantDate {
    /// Unique, non-persistent Api Id for this resource
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name/Title of the Important Date
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Optional description of the Important Date, can contain markup
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The type category this Important Date belongs to
    #[serde(rename = "importantDateType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub important_date_type: Option<Option<String>>,
    /// Details about terms, dates, and special notes
    #[serde(rename = "details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details: Option<Option<Vec<crate::models::ImportantDateDetails>>>,
    /// Keywords associated with the Important Date
    #[serde(rename = "keywords", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Option<Vec<String>>>,
    /// Audiences associated with the Important Date
    #[serde(rename = "audiences", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub audiences: Option<Option<Vec<String>>>,
}

impl ImportantDate {
    /// An Important Date is an event at a time that has significance to the Waterloo community
    pub fn new() -> ImportantDate {
        ImportantDate {
            id: None,
            name: None,
            description: None,
            important_date_type: None,
            details: None,
            keywords: None,
            audiences: None,
        }
    }
}


