/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 *
 * Generated by: https://openapi-generator.tech
 */

/// LocationGeo : Model representing a Location for the Buildings dataset in GEO JSON format

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LocationGeo {
    /// Type property of GEO JSON collection
    #[serde(
        rename = "type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#type: Option<Option<String>>,
    /// Features of this collection
    #[serde(
        rename = "features",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub features: Option<Option<Vec<crate::models::Feature>>>,
}

impl LocationGeo {
    /// Model representing a Location for the Buildings dataset in GEO JSON format
    pub fn new() -> LocationGeo {
        LocationGeo {
            r#type: None,
            features: None,
        }
    }
}
