/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Locpick {
    #[serde(rename = "user_latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_latitude: Option<Option<String>>,
    #[serde(rename = "user_longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_longitude: Option<Option<String>>,
}

impl Locpick {
    pub fn new() -> Locpick {
        Locpick {
            user_latitude: None,
            user_longitude: None,
        }
    }
}


