/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Und {
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    #[serde(rename = "revision_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revision_id: Option<Option<String>>,
}

impl Und {
    pub fn new() -> Und {
        Und {
            value: None,
            revision_id: None,
        }
    }
}


