/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Value {
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    #[serde(rename = "follow", skip_serializing_if = "Option::is_none")]
    pub follow: Option<i32>,
    #[serde(rename = "noindex", skip_serializing_if = "Option::is_none")]
    pub noindex: Option<i32>,
    #[serde(rename = "nofollow", skip_serializing_if = "Option::is_none")]
    pub nofollow: Option<i32>,
    #[serde(rename = "noarchive", skip_serializing_if = "Option::is_none")]
    pub noarchive: Option<i32>,
    #[serde(rename = "nosnippet", skip_serializing_if = "Option::is_none")]
    pub nosnippet: Option<i32>,
    #[serde(rename = "noodp", skip_serializing_if = "Option::is_none")]
    pub noodp: Option<i32>,
    #[serde(rename = "noydir", skip_serializing_if = "Option::is_none")]
    pub noydir: Option<i32>,
    #[serde(rename = "noimageindex", skip_serializing_if = "Option::is_none")]
    pub noimageindex: Option<i32>,
    #[serde(rename = "notranslate", skip_serializing_if = "Option::is_none")]
    pub notranslate: Option<i32>,
}

impl Value {
    pub fn new() -> Value {
        Value {
            index: None,
            follow: None,
            noindex: None,
            nofollow: None,
            noarchive: None,
            nosnippet: None,
            noodp: None,
            noydir: None,
            noimageindex: None,
            notranslate: None,
        }
    }
}


